version: '3.8'

services:
  db:
    image: postgres
    container_name: books_read_db
    environment:
      POSTGRES_USER: books_read_user
      POSTGRES_PASSWORD: senha123
      POSTGRES_DB: books_read_development
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: